modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="${mod_id}" # The modid of the mod
    version="${mod_version}" # The version number of the mod
    displayName="${mod_name}" # A display name for the mod
    authors="${mod_authors}"
    description='''${mod_description}''' # The description text for the mod (multi line!)
## Dependencies
[[dependencies.${mod_id}]]
    modId="forge" # The modid of the dependency
    mandatory=true  # Does this dependency have to exist
    versionRange="${forge_version_range}" # The version range of the dependency
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT, or SERVER
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}" # This version range declares a minimum of the current minecraft version up to but not including the next major version
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"